# Generated by Django 4.2.5 on 2023-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svyzimod', '0002_user_alter_product_obym_upakov_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='obym_upakov',
            field=models.IntegerField(null=True),
        ),
    ]
